# Generated by Django 3.2.11 on 2022-01-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220114_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tax',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Checks'), (3, 'Debit Cards'), (4, 'Credit Cards'), (5, 'Mobile Payments'), (6, 'Electronic Bank Transfer')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[(0, 'No Tax'), (1, 'Individual Income Taxes'), (2, 'Corporate Income Taxes'), (3, 'Payroll Taxes'), (4, 'Capital Gains Taxes'), (5, 'Sales Taxes'), (6, 'Gross Receipts Taxes'), (7, 'Value Added Taxes'), (8, 'Excise Taxes')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='shippping',
            name='cost',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='shippping',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
